repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: double-quote-string-fixer
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
    -   id: autopep8
-   repo: https://github.com/pre-commit/pre-commit
    rev: v1.21.0
    hooks:
    -   id: validate_manifest
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.25.3
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.9.0
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v1.5.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.6.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
    -   id: mypy
        exclude: ^testing/resources/
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
repos:
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      args: [--safe, --quiet]
      exclude: tests/functional/|tests/input|tests/extensions/data|tests/regrtest_data/|tests/data/
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.3.1
    hooks:
    -   id: pylint
        args:
        - --max-line-length=100
        - --ignore-imports=yes
        - -d duplicate-code